# This is a basic workflow to test a self hosted runner
name: GH-SHR Hello World

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - 'test_gh_shr'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello"
  hello:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Say hello
    - name: Say Hello
      run: echo "Hello World!"
